language: python
sudo: required
dist: xenial

python:
  - "3.7"
  - "3.6"
  - "3.5"

matrix:
  fast_finish: true

jobs:
  - stage: deploy
    if: tag IS present
    python: "3.6"
    install: skip
    script: skip
    deploy:
      skip_cleanup: true
    - provider: pypi
      user: $PYPI_USERNAME
      password: $PYPI_PASSWORD
      distributions: sdist bdist_wheel
      on:
        tags: true

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "npm install -g webpack-cli"
  - "npm install -g webpack"
  - "npm install --prefix ./robotpy_websim/html/"
# command to create build 
script:
  - "npm run --prefix ./robotpy_websim/html/ build:prod"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2fb1c026e64fdd70d27b
    on_success: change
    on_failure: always
    on_start: never